### ISSUE TITLE
Outstanding

### ISSUE THREAD

**Issue by Lahrenheit** [AlexsanderRST/edopro-hd-cards-downloader#2]
Hi alex, how are u? Really a must-have software for hd pics, tomorrow I'll try to share you an all-cards.ydk updated from all edopro's cards (too the character ones btw I think that these not will be downloaded, not tested).
Keep it up! And it will be awesome implement hd fields in a future
Greetings

- Lahrenheit

Edit: 
[allcards-all.zip](https://github.com/AlexsanderRST/edopro-hd-cards-downloader/files/5803093/allcards-all.zip)

**Comment by AlexsanderRST** [comment]
Hey, I'm fine!
I left the project aside lately, but this week I'm going to do some updates. Two things:
- You can send the ydk;
- The field's artworks, if downloaded from the database I use, are approximately 22% wider and higher than those of the game, that is, it will not make as much difference as it did with the card's pics. But I will implement it anyway.

**Comment by Lahrenheit** [comment]
![Sin título](https://user-images.githubusercontent.com/67435388/104337483-4e656580-54d4-11eb-80cc-c3c487da84b7.png)

This error appear when I try to load my allcards.ydk, I think that is becuase some cards not exists in database?

**Comment by AlexsanderRST** [comment]
I just uploaded a new version that deals with this kind of problem, download it (exe or py) and try again. If the error persists, send me the .ydk for me to check it out.

**Comment by Lahrenheit** [comment]
I've downloaded again, and appear this now:

![asd](https://user-images.githubusercontent.com/67435388/104351823-a7d59080-54e4-11eb-81b0-0651b6ee0421.png)

[allcardsmio.zip](https://github.com/AlexsanderRST/edopro-hd-cards-downloader/files/5803858/allcardsmio.zip)

**Comment by AlexsanderRST** [comment]
Thanks for reporting. This error is caused by the function's way of handling a ydk. The old versions did not deal with nonexistent urls and therefore the entry had to be perfect. The new versions made this code snippet obsolete and I hadn't removed it because I was dealing with regular ydks. I just posted a new version that corrects this error.

**Comment by Lahrenheit** [comment]
Thank you, I've downloaded it and seem works fine till now, I'll let it downloading and I'll report here if there isn't problem at all; I'll wait for your new version with fields pics ^^

**Comment by AlexsanderRST** [comment]
I am working on some tools that will make allcards.ydk's update easy. As soon as I finish them, I upload the file.

**Comment by Lahrenheit** [comment]
The app crash at ~2300 card counting so I'll try with /allcards command, fields too stuck at 13 or 94 counting for me, I checked my conection but it works perfectly, ths will be related to a time stamp or idling? thanks!
